### ISSUE TITLE
Reading : New header row is added every time while new sheet data is appended

### ISSUE THREAD

**Issue by jaypanchal** [ZuInnoTe/spark-hadoopoffice-ds#13]
![screenshot from 2018-03-05 15-40-43](https://user-images.githubusercontent.com/17511552/36969802-8e2db53e-208c-11e8-935a-cbf32abb9437.png)
For instance if i am choosing useHeader true and pass a file or multiple files with multiple sheets but all sheets and files has exactly same number of columns with same name and datatype, then final datasets contains additional new row at start of new sheet data.

E.g. 3 files with 2 sheets in each, total 6 sheets, so final dataset will have 5 additional rows, from each sheet's first row as a "data row"

**Comment by jornfranke** [comment]
I see. For the current version you have the option to filter sheets so you could have for each dataframe one filter for each sheet.

I could imagine we could set a configuration that header should be read / sheet. This could be included in future versions.

**Comment by jornfranke** [comment]
Multiple files => in this case the header should be already skipped, because it is skipped for each file. Can you confirm that this is not the case?
Multiple sheets in a single file: You can pass the HadoopOffice option "hadoopoffice.read.sheets" where you just specify one sheet / data frame. In this way you can already today skip the header for each sheet, because you load each sheet individually. However, it also implies that the file is loaded x times and x corresponds to the number of sheets in a file.

for the latter case we can include an option read.spark.useHeader.skipHeaderInEachSheet

**Comment by jaypanchal** [comment]
Yes, for multiple files headers are not skipped...

I will make sure and let you read.spark.useHeader.skipHeaderInEachSheet is working fine or not. :) thnks

**Comment by jornfranke** [comment]
ok, i look a little bit into it. It is feasible, but I have to give a little bit thought to make this feature more general. The reason is that we soon also will release this library for Hive, Flink DataSource/DataSink and Flink TableSource/TableSink API.

**Comment by jornfranke** [comment]
released in 1.1.0

check readme.md, please confirm

**Comment by jornfranke** [comment]
please create a new issue if it does not meet your use case
