### ISSUE TITLE
lowFootprint: numeric column values result in nulls

### ISSUE THREAD

**Issue by Pooj2** [ZuInnoTe/spark-hadoopoffice-ds#31]
with spark-hadoopoffice-ds v1.3.5 lowFootprint parser returns numeric columns content as _null_s.

with spark-hadoopoffice-ds v1.3.5 an spreadsheetml 2006 format xlsx files numeric columns leads to a:
`XSSFPullParser.getNext: Cannot read celltype            line: org.zuinnote.hadoop.office.format.common.parser.msexcel.internal.XSSFPullParser.getNext(XSSFPullParser.java:192` which result in a _null_ instead of the numeric value.

The cause of this is the missing of t-attributes in the c-elements in the contents of /xl/worksheets/sheet1.xml. Take for example a look at the cells H1 through H5 and Q1 through Q5. The values are:
Cell Value
H1  empty
H2  a string 
H3  1
H4  25
H5  25
Q1  empty
Q2  a string 
Q3  1
Q4  8
Q5  2

The numeric values above correspond to the value of the worksheet-sheetData-row-c-v elements (see 
[spreadsheetml2006mainpartial.xml.txt](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/3803182/spreadsheetml2006mainpartial.xml.txt))

This issue is reproducible with a http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac spreadsheet so see ([MapIssue31.xlsx](https://github.com/ZuInnoTe/spark-hadoopoffice-ds/files/3803468/MapIssue31.xlsx)).

The numeric value of the cell is located as String at the XMLEvent CharactersEventImpl.mContent from xer.nextEvent().

It would be nice when the value of the v-elements is returned instead of the current _null_s.

Updated with an example to reproduce.

**Comment by jornfranke** [comment]
Thx I will look into this

**Comment by jornfranke** [comment]
I see where the issue is and i think your proposal makes sense. i hope latest by end of the week i have 1.3.6 out to patch this.

Thanks for reporting with the good amount of detail - very much appreciated.

As a workaround (if you cannot wait this week) then you can use the SAX parser (https://github.com/ZuInnoTe/hadoopoffice/wiki/Hadoop-File-Format#low-footprint-mode), but it is not as memory efficient as the default Stax parser.

**Comment by Pooj2** [comment]
Thnx. and thanks for the SAX suggestion. I'm hoping to start a dev run with a big sheet in a couple of hours.

**Comment by jornfranke** [comment]
I did a small fix and will publish it as 1.3.6 in the coming days. If no type is found it will return the values as String. They will then be converted by the converter in Spark HadoopOffice into numbers if you use simpelMode.
You saw null, because an empty string was returned instead of the numbers.

**Comment by jornfranke** [comment]
I published 1.3.6, please let me know if it works for you - thank you

**Comment by Pooj2** [comment]
Thnx. **Fixed.**
The problem described above as is fixed with 1.3.6.

**Comment by jornfranke** [comment]
thank you for the feedback and the detailed report
